name: Auto Deploy

on:
  push:
      branches: [master]

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        # - uses: actions/setup-node@v1
        #   with:
        #     node-version: '14'
        # - name: Install Yarn
        #   run: npm install -g yarn
        # - name: Building
        #   run: |
        #     yarn && BUILDING=true yarn run nuchain:build
        - name: Deploying
          uses: burnett01/rsync-deployments@4.1
          with:
            switches: -avzrhcP --delete-after --include="" --filter=""
            path: website/build/nuchain-wiki/
            remote_path: /home/www/nuchain-wiki
            remote_host: ${{ secrets.DEPLOY_HOST }}
            remote_user: ${{ secrets.DEPLOY_USER }}
            remote_key: ${{ secrets.DEPLOY_KEY }}
